/**
 * Application-specific error codes.
 * Used in ApiError to provide machine-readable error identification.
 */
export const ERROR_CODES = Object.freeze({
  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Authentication & Authorization
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_EMAIL_EXISTS: 'AUTH_EMAIL_EXISTS',

  // Resources
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',

  // Courses
  COURSE_NOT_FOUND: 'COURSE_NOT_FOUND',
  COURSE_SLUG_EXISTS: 'COURSE_SLUG_EXISTS',

  // Modules
  MODULE_NOT_FOUND: 'MODULE_NOT_FOUND',
  MODULE_LOCKED: 'MODULE_LOCKED',

  // Topics
  TOPIC_NOT_FOUND: 'TOPIC_NOT_FOUND',
  TOPIC_LOCKED: 'TOPIC_LOCKED',

  // Stories
  STORY_NOT_FOUND: 'STORY_NOT_FOUND',

  // Explainers
  EXPLAINER_NOT_FOUND: 'EXPLAINER_NOT_FOUND',

  // Games
  GAME_NOT_FOUND: 'GAME_NOT_FOUND',
  GAME_ALREADY_EXISTS: 'GAME_ALREADY_EXISTS',

  // Users
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // AI
  AI_PROVIDER_ERROR: 'AI_PROVIDER_ERROR',
  AI_QUOTA_EXCEEDED: 'AI_QUOTA_EXCEEDED',

  // Progress
  PROGRESS_NOT_FOUND: 'PROGRESS_NOT_FOUND',
});
